; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
;
; This example is a PlatformIO project, and building it requires PlatformIO: 
; https://platformio.org/install
;
; ============================================================
; TO USE YOUR OWN BOARD, set:
;   1. platform - your MCU family/toolchain (below is Espressif ESP32)
;   2. board    - your specific board id: https://docs.platformio.org/en/latest/boards
;   3. [env:amu_dev_s3] below configures native USB (CDC/JTAG) upload/logging -
;      if your board doesn't have native USB, delete that whole section
; ============================================================
[env]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.39
board = um_tinys3
framework = arduino

; AMU Library Configuration:
; Local development -> Comment amulib git and use symlink
; Production -> Comment symlink and use amulib git
lib_deps =
	symlink://../../
; 	https://github.com/the-aerospace-corporation/amulib.git

build_flags =
	'-I./include'
	'-DAMU_BAUD_RATE=${this.monitor_speed}'

monitor_speed = 115200
monitor_eol = LF
monitor_raw = yes
monitor_echo = false ; Disabled to prevent terminal output being sent to device

[env:amu_dev_s3]

board_upload.wait_for_upload_port = false ; Waiting isn't needed for CDC/JTAG USB mode

build_flags =
	${env.build_flags}
    '-DARDUINO_USB_MODE=1' ; CDC/JTAG USB mode
	'-DARDUINO_USB_CDC_ON_BOOT=1'