; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
platform = https://github.com/pioarduino/platform-espressif32.git#53.03.13
board = um_tinys3
framework = arduino
board_upload.wait_for_upload_port = false ; Waiting isn't needed for CDC/JTAG USB mode

; For production or when using a specific amulib version, comment out lib_extra_dirs
; and add the url lib_deps to use the git repository:
lib_deps =
	Wire
	SPI
	thomasfredericks/Bounce2@^2.72
 	; https://github.com/the-aerospace-corporation/amulib.git

build_flags =
	'-I./include'

; For local development with amulib modifications, use lib_extra_dirs:
lib_extra_dirs =
	../../

[env:amu_dev_s3]

build_flags =
	${env.build_flags}
    '-DARDUINO_USB_MODE=1' ; CDC/JTAG USB mode
	'-DARDUINO_USB_CDC_ON_BOOT=1'
    '-DCORE_DEBUG_LEVEL=0'
	'-DCONFIG_LOG_COLORS=1'
	'-DCONFIG_ARDUHAL_LOG_COLORS=1'

lib_deps =
    ${env.lib_deps}
    unexpectedmaker/UMS3 Helper@^1.1.1

monitor_raw = yes
monitor_echo = false ; Disabled to prevent terminal output being sent to device
monitor_eol = LF

monitor_speed = 115200