name=amulib
version=3.0.0
author=Colin Mann
maintainer=Colin Mann
sentence=Library for communicating with AMU devices
paragraph=Supports multiple AMUs on I2C bus as well as AMU_DEVICE construction for utilizing SCPI based communication with host device.
category=Device Control
url=https://aerospace.org
architectures=*
license=MIT
