#ifndef AMULIB_VERSION_H
#define AMULIB_VERSION_H

#define AMULIB_VERSION_MAJOR 3
#define AMULIB_VERSION_MINOR 0
#define AMULIB_VERSION_PATCH 0

#define AMULIB_GIT_COMMIT "a944466"
#define AMULIB_GIT_BRANCH "fix/scpi-transfer-lengths"
#define AMULIB_GIT_DIRTY 1
#define AMULIB_GIT_COMMIT_COUNT 83

#define AMULIB_BUILD_TIMESTAMP "2026-08-03 04:00:45"

#define AMULIB_VERSION_BUILD "3.0.0.83"
#define AMULIB_VERSION_FULL "v3.0.0+git.a944466-dirty"
#define AMULIB_VERSION_SEMANTIC "3.0.0"
#define AMULIB_VERSION_SHORT "v3.0.0-a944466*"

#define AMULIB_VERSION_STR AMULIB_VERSION_SEMANTIC
#define AMULIB_VERSION_STR_LEN 25

#endif // AMULIB_VERSION_H
