#ifndef AMULIB_VERSION_H
#define AMULIB_VERSION_H

#define AMULIB_VERSION_MAJOR 1
#define AMULIB_VERSION_MINOR 0
#define AMULIB_VERSION_PATCH 0
#define AMULIB_VERSION_SEMANTIC "1.0.0"

#define AMULIB_GIT_COMMIT "7ed9f32"
#define AMULIB_GIT_BRANCH "main"
#define AMULIB_GIT_DIRTY 1
#define AMULIB_GIT_COMMIT_COUNT 77

#define AMULIB_BUILD_TIMESTAMP "2026-07-07 09:19:49"

#define AMULIB_VERSION_BUILD "1.0.0.77"
#define AMULIB_VERSION_COMPACT "v1.0.0-7ed9f32*"
#define AMULIB_VERSION_FULL "v1.0.0+git.7ed9f32-dirty"
#define AMULIB_VERSION_MINIMAL "1.0.0"

#define AMULIB_VERSION_STR AMULIB_VERSION_FULL
#define AMULIB_VERSION_STR_LEN 25

#endif // AMULIB_VERSION_H
